id: b909f085-9fb6-4d2f-82ca-4ab8c37c19c1
name: PSOC - Detects suspicious child processes of the Microsoft OneNote application
kind: Scheduled
description: |-
  Detects suspicious child processes of Microsoft OneNote
  This could happen if a user is phished with a onenote attachment
severity: High
queryFrequency: 5m
queryPeriod: 30m
triggerOperator: gt
triggerThreshold: 0
tactics:
- InitialAccess
relevantTechniques:
- T1566
query: |-
  // Detects suspicious child processes of Microsoft OneNote
  let ProcessNames = dynamic(["explorer.exe"]);
  let parent_processes = dynamic(["onenote.exe"]);
  let cmd_all = dynamic(["ifm","create full"]);
  let cmd_any = dynamic([".hta",".vb",".wsh",".js",".ps",".scr",".pif",".bat",".cmd"]);
  _Im_ProcessCreate(targetprocess_has_any=ProcessNames,parentprocess_has_any=parent_processes,commandline_has_any=cmd_any)
  | extend
      Account = tostring(column_ifexists("ActorUsername", "")),
      AccountDomain = tostring(column_ifexists("ActorUserDomain", "")),
      Computer = tostring(column_ifexists("DvcHostname", "")),
      ProcessName = tostring(column_ifexists("TargetProcessName", "")),
      ProcessId = tostring(column_ifexists("TargetProcessId", "")),
      CommandLine = tostring(column_ifexists("CommandLine", ""))
  | where isnotempty(ProcessName)
entityMappings:
- entityType: Account
  fieldMappings:
  - identifier: Name
    columnName: Account
  - identifier: NTDomain
    columnName: AccountDomain
- entityType: Host
  fieldMappings:
  - identifier: HostName
    columnName: Computer
- entityType: Process
  fieldMappings:
  - identifier: ProcessId
    columnName: ProcessId
  - identifier: CommandLine
    columnName: CommandLine
suppressionEnabled: false
suppressionDuration: 5h
eventGroupingSettings:
  aggregationKind: SingleAlert
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: true
    reopenClosedIncident: false
    lookbackDuration: 5h
    matchingMethod: AllEntities
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails: []

